/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Enum.java to edit this template
 */
package communication;

/**
 *
 * @author milan
 */
public enum Operation {
    LOGIN,KREIRAJ_INSTRUKTOR,PROMENI_INSTRUKTOR,OBRISI_INSTRUKTOR,UCITAJ_INSTRUKTOR,UCITAJ_INSTRUKTOR_FILTER,
    UCITAJ_LICENCA,UCITAJ_LICENCA_FILTER,KREIRAJ_LICENCA,OBRISI_LICENCA,PROMENI_LICENCA,
    UCITAJ_INSTRUKTOR_LICENCA,UCITAJ_INSTRUKTOR_LICENCA_FILTER,KREIRAJ_INSTRUKTOR_LICENCA,OBRISI_INSTRUKTOR_LICENCA,
    UCITAJ_NIVO_SKIJANJA,UCITAJ_NIVO_SKIJANJA_FILTER,KREIRAJ_NIVO_SKIJANJA,OBRISI_NIVO_SKIJANJA,PROMENI_NIVO_SKIJANJA,
    UCITAJ_TIP_TERMINA,UCITAJ_TIP_TERMINA_FILTER,KREIRAJ_TIP_TERMINA,PROMENI_TIP_TERMINA,OBRISI_TIP_TERMINA,
    UCITAJ_SKIJAS,UCITAJ_SKIJAS_FILTER,KREIRAJ_SKIJAS,PROMENI_SKIJAS,OBRISI_SKIJAS,
    UCITAJ_TERMIN,UCITAJ_TERMIN_FILTER,KREIRAJ_TERMIN,PROMENI_TERMIN,OBRISI_TERMIN,
    UCITAJ_TERMIN_SKIJAS,UCITAJ_TERMIN_SKIJAS_FILTER,KREIRAJ_TERMIN_SKIJAS,PROMENI_TERMIN_SKIJAS,OBRISI_TERMIN_SKIJAS;
}
